# Site settings
author: Dominick D'Andrea
title: 
header-img: img/home-bg.png
email: ddandrea@reagan.com
copyright_name: Dominick D'Andrea
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dandread

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
